local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 5
   publish_frequency: 5
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.01
   transform_tolerance: 6.0
   origin_x: -50.0
   origin_y: -50.0
